In [145]:
import pandas
import numpy

In [114]:
dataf=pandas.read_csv("train.csv",skiprows=[1],encoding = "ISO-8859-1")

In [115]:
#dataf.head()

In [116]:
#dataf.info() #16, 63 total cols

In [117]:
dataf=dataf.fillna(0)
#dataf.fillNaN(0)

In [391]:
dataf.iloc[:,7]=dataf.iloc[:,7].replace(["Male","Female","Both","0"],['1','2','3','4'])
dataf.iloc[:,8]=dataf.iloc[:,8].replace(['Solo', 'Group', 0],['1','2','3'])
dataf.iloc[:,13]=dataf.iloc[:,13].replace(['Away', 'Home'],['1','2'])
dataf.iloc[:,14]=dataf.iloc[:,14].replace(['Away', 'Home'],['1','2'])
#dataf.iloc[:,0:20]

TypeError: Cannot compare types 'ndarray(dtype=int64)' and 'str'

In [119]:
dataf.iloc[:,13].unique()
#dataf.iloc[:,8]

array(['1', '2'], dtype=object)

In [120]:
m1=dataf.iloc[:,1].unique()
dataf.iloc[:,1]=dataf.iloc[:,1].replace(['United Kingdom', 'Albania', 'Germany', 'Armenia',
       'Bosnia and Herzegovina', 'Israel', 'Finland ', 'Croatia', 'Poland',
       'Iceland', 'Turkey', 'Portugal', 'Latvia', 'Sweden', 'Denmark',
       'Georgia', 'Ukraine', 'France', 'Azerbaijan', 'Greece', 'Spain',
       'Serbia', 'Russia', 'Norway', 'Belarus', 'Ireland', 'Macedonia',
       'Slovenia', 'Hungary', 'Lithuania', 'Romania', 'Bulgaria',
       'Moldova', 'Switzerland', 'Malta', 'Cyprus',
       'Serbia and Montenegro', 'Austria', 'Netherlands', 'Belgium',
       'Estonia', 'Finland', 'Slovakia'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42])


In [121]:
#dataf.iloc[:,2].unique()
#dataf.iloc[:,1]
dataf.iloc[:,2]=dataf.iloc[:,2].replace(['Independent', 'Former Socialist Bloc', 'Western Europe',
       'Former Yugoslavia', 'Scandinavia'],[0,1,2,3,4])

In [123]:
dataf

Year  Country     Region                     Song language  \
0    2008           0       0                           English   
1    2008           1       1                          Albanian   
2    2008           2       2                           English   
3    2008           3       1                 English, Armenian   
4    2008           4       3                           Bosnian   
5    2008           5       0                   Hebrew, English   
6    2008           6       4                           Finnish   
7    2008           7       3                          Croatian   
8    2008           8       1                           English   
9    2008           9       4                           English   
10   2008          10       0                           Turkish   
11   2008          11       2                        Portuguese   
12   2008          12       1                           English   
13   2008          13       4                           English   
14   2008          14       4                           English   
15   2008          15       1                           English   
16   2008          16       1                           English   
17   2008          17       2                   English, French   
18   2008          18       1                           English   
19   2008          19       2                           English   
20   2008          20       2                  Spanish, English   
21   2008          21       3                           Serbian   
22   2008          22       1                           English   
23   2008          23       4                           English   
24   2007           4       3                           Bosnian   
25   2007          20       2                  Spanish, English   
26   2007          24       1                           English   
27   2007          25       0                           English   
28   2007           6       4                           English   
29   2007          26       3               Macedonian, English   
..    ...         ...     ...                               ...   
235  1999           5       0                   English, Hebrew   
236  1999          34       2                           English   
237  1999           2       2  German, Turkish, Hebrew, English   
238  1999           4       3                   Bosnian, French   
239  1999          40       1                           English   
240  1998           7       3                          Croatian   
241  1998          19       2                             Greek   
242  1998          17       2                            French   
243  1998          20       2                           Spanish   
244  1998          33       2                            German   
245  1998          42       1                            Slovak   
246  1998           8       1                            Polish   
247  1998           5       0                            Hebrew   
248  1998           2       2                            German   
249  1998          34       2                           English   
250  1998          28       1                         Hungarian   
251  1998          27       3                           Slovene   
252  1998          25       0                           English   
253  1998          11       2                        Portuguese   
254  1998          30       1                          Romanian   
255  1998           0       0                           English   
256  1998          35       0                             Greek   
257  1998          38       2                             Dutch   
258  1998          13       4                           Swedish   
259  1998          39       2                            French   
260  1998          41       0                           Finnish   
261  1998          23       4                         Norwegian   
262  1998          40       1                       

In [124]:
dataf.iloc[:,11]=dataf.iloc[:,11].replace(['United Kingdom', 'Albania', 'Germany', 'Armenia',
       'Bosnia and Herzegovina', 'Israel', 'Finland ', 'Croatia', 'Poland',
       'Iceland', 'Turkey', 'Portugal', 'Latvia', 'Sweden', 'Denmark',
       'Georgia', 'Ukraine', 'France', 'Azerbaijan', 'Greece', 'Spain',
       'Serbia', 'Russia', 'Norway', 'Belarus', 'Ireland', 'Macedonia',
       'Slovenia', 'Hungary', 'Lithuania', 'Romania', 'Bulgaria',
       'Moldova', 'Switzerland', 'Malta', 'Cyprus',
       'Serbia and Montenegro', 'Austria', 'Netherlands', 'Belgium',
       'Estonia', 'Finland', 'Slovakia'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42])


In [127]:
dataf.iloc[:,12]=dataf.iloc[:,12].replace(['Independent', 'Former Socialist Bloc', 'Western Europe',
       'Former Yugoslavia', 'Scandinavia'],[0,1,2,3,4])

TypeError: Cannot compare types 'ndarray(dtype=int64)' and 'str'

In [164]:
len(dataf.iloc[:,3].unique())
dataf['English_lang']=numpy.where(dataf.iloc[:,3].str.contains("English",case=False),1,0)
dataf['Hebrew_lang']=numpy.where(dataf.iloc[:,3].str.contains("Hebrew",case=False),1,0)
dataf['Macedonian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Macedonian",case=False),1,0)
dataf['Italian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Italian",case=False),1,0)
dataf['German_lang']=numpy.where(dataf.iloc[:,3].str.contains("German",case=False),1,0)
dataf['Styrian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Styrian",case=False),1,0)
dataf['Serbian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Serbian",case=False),1,0)
dataf['Greek_lang']=numpy.where(dataf.iloc[:,3].str.contains("Greek",case=False),1,0)
dataf['Slovak_lang']=numpy.where(dataf.iloc[:,3].str.contains("Slovak",case=False),1,0)
dataf['Albanian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Albanian",case=False),1,0)
dataf['French_lang']=numpy.where(dataf.iloc[:,3].str.contains("French",case=False),1,0)
dataf['Romanian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Romanian",case=False),1,0)
dataf['Croatian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Croatian",case=False),1,0)
dataf['Polish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Polish",case=False),1,0)
dataf['Lithuanian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Lithuanian",case=False),1,0)
dataf['Maltese_lang']=numpy.where(dataf.iloc[:,3].str.contains("Maltese",case=False),1,0)
dataf['Finnish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Finnish",case=False),1,0)
dataf['Spanish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Spanish",case=False),1,0)
dataf['Slovene_lang']=numpy.where(dataf.iloc[:,3].str.contains("Slovene",case=False),1,0)
dataf['Norwegian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Norwegian",case=False),1,0)
dataf['Montenegrin_lang']=numpy.where(dataf.iloc[:,3].str.contains("Montenegrin",case=False),1,0)
dataf['Russian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Russian",case=False),1,0)
dataf['Bosnian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Bosnian",case=False),1,0)
dataf['Turkish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Turkish",case=False),1,0)
dataf['Dutch_lang']=numpy.where(dataf.iloc[:,3].str.contains("Dutch",case=False),1,0)
dataf['Armenian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Armenian",case=False),1,0)
dataf['Ukrainian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Ukrainian",case=False),1,0)
dataf['Portuguese_lang']=numpy.where(dataf.iloc[:,3].str.contains("Portuguese",case=False),1,0)
dataf['Imaginary_lang']=numpy.where(dataf.iloc[:,3].str.contains("Imaginary",case=False),1,0)
dataf['Swedish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Swedish",case=False),1,0)
dataf['Samogitian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Samogitian",case=False),1,0)
dataf['Estonian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Estonian",case=False),1,0)
dataf['Hungarian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Hungarian",case=False),1,0)


In [392]:
#dataf['eng_lang']
#dataf.iloc[:,3].unique()
#dataf

In [211]:
#dataf_final=dataf[:,-3]
#type(dataf)
del dataf['Song language']
#dataf.columns.values
del dataf['Artist   ']
del dataf['Song   ']
del dataf['English translation ']
del dataf['eng_lang']

KeyError: 'Song language'

In [337]:
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from keras.models import model_from_json

In [225]:
dataframe=dataf
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
dataset = dataframe.values

In [258]:
#len(dataframe.columns.values)
# split into input (X) and output (Y) variables
#dataframe.iloc[:,59:91]
X_df = pandas.concat([dataframe.iloc[:,0:12].reset_index(drop=True), dataframe.iloc[:,59:92]], axis=1)
#Y = dataset[:,13]
#X_df.columns.values
Y_df=dataframe.iloc[:,12:59]
#Y_df.columns.values
#len(X_df.columns.values)
#len(Y_df.columns.values)


In [405]:
X=X_df.values
Y=Y_df.iloc[:,0].values
type(Y)
outs=len(Y_df.iloc[:,0].unique())
ins=len(X_df.columns.values)


In [407]:
Y_df.columns.values[0]


'Albania '

In [328]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)
def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(16, input_dim=ins, activation='relu'))
	model.add(Dense(outs, activation='softmax'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print("Accuracy: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Accuracy: 24.30% (35.62%)


In [335]:
model = baseline_model()
model.fit(X, dummy_y, nb_epoch=200, batch_size=5, verbose=0)



C:\Anaconda2\envs\videoken\lib\site-packages\keras\models.py:848: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


In [341]:
def save_model(model):
    # saving model
    json_model = model.to_json()
    open('model_architecture.json', 'w').write(json_model)
    # saving weights
    model.save_weights('model_weights.h5', overwrite=True)

def load_model():
    # loading model
    model = model_from_json(open('model_architecture.json').read())
    model.load_weights('model_weights.h5')
    model.compile(loss='categorical_crossentropy', optimizer='adam')
    return model
# save
save_model(model)

# load
model = load_model()


In [358]:

datat=pandas.read_csv("test.csv",skiprows=[1],encoding = "ISO-8859-1")
datat=datat.fillna(0)
#datat.fillNaN(0)
datat.iloc[:,7]=datat.iloc[:,7].replace(["Male","Female","Both","0"],['1','2','3','4'])
datat.iloc[:,8]=datat.iloc[:,8].replace(['Solo', 'Group', 0],['1','2','3'])
datat.iloc[:,13]=datat.iloc[:,13].replace(['Away', 'Home'],['1','2'])
datat.iloc[:,14]=datat.iloc[:,14].replace(['Away', 'Home'],['1','2'])
datat.iloc[:,0:20]
m1=datat.iloc[:,1].unique()
datat.iloc[:,1]=datat.iloc[:,1].replace(['United Kingdom', 'Albania', 'Germany', 'Armenia',
       'Bosnia and Herzegovina', 'Israel', 'Finland ', 'Croatia', 'Poland',
       'Iceland', 'Turkey', 'Portugal', 'Latvia', 'Sweden', 'Denmark',
       'Georgia', 'Ukraine', 'France', 'Azerbaijan', 'Greece', 'Spain',
       'Serbia', 'Russia', 'Norway', 'Belarus', 'Ireland', 'Macedonia',
       'Slovenia', 'Hungary', 'Lithuania', 'Romania', 'Bulgaria',
       'Moldova', 'Switzerland', 'Malta', 'Cyprus',
       'Serbia and Montenegro', 'Austria', 'Netherlands', 'Belgium',
       'Estonia', 'Finland', 'Slovakia'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42])

#datat.iloc[:,2].unique()
#datat.iloc[:,1]

In [359]:
datat.iloc[:,2]=datat.iloc[:,2].replace(['Independent', 'Former Socialist Bloc', 'Western Europe','Former Yugoslavia', 'Scandinavia'],[0,1,2,3,4])
datat.iloc[:,11]=datat.iloc[:,11].replace(['United Kingdom', 'Albania', 'Germany', 'Armenia','Bosnia and Herzegovina', 'Israel', 'Finland ', 'Croatia', 'Poland','Iceland', 'Turkey', 'Portugal', 'Latvia', 'Sweden', 'Denmark','Georgia', 'Ukraine', 'France', 'Azerbaijan', 'Greece', 'Spain','Serbia', 'Russia', 'Norway', 'Belarus', 'Ireland', 'Macedonia','Slovenia', 'Hungary', 'Lithuania', 'Romania', 'Bulgaria','Moldova', 'Switzerland', 'Malta', 'Cyprus','Serbia and Montenegro', 'Austria', 'Netherlands', 'Belgium','Estonia', 'Finland', 'Slovakia'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42])


In [360]:
datat.iloc[:,12]=datat.iloc[:,12].replace(['Independent', 'Former Socialist Bloc', 'Western Europe','Former Yugoslavia', 'Scandinavia'],[0,1,2,3,4])
len(datat.iloc[:,3].unique())
datat['English_lang']=numpy.where(datat.iloc[:,3].str.contains("English",case=False),1,0)
datat['Hebrew_lang']=numpy.where(datat.iloc[:,3].str.contains("Hebrew",case=False),1,0)
datat['Macedonian_lang']=numpy.where(datat.iloc[:,3].str.contains("Macedonian",case=False),1,0)
datat['Italian_lang']=numpy.where(datat.iloc[:,3].str.contains("Italian",case=False),1,0)
datat['German_lang']=numpy.where(datat.iloc[:,3].str.contains("German",case=False),1,0)
datat['Styrian_lang']=numpy.where(datat.iloc[:,3].str.contains("Styrian",case=False),1,0)
datat['Serbian_lang']=numpy.where(datat.iloc[:,3].str.contains("Serbian",case=False),1,0)
datat['Greek_lang']=numpy.where(datat.iloc[:,3].str.contains("Greek",case=False),1,0)
datat['Slovak_lang']=numpy.where(datat.iloc[:,3].str.contains("Slovak",case=False),1,0)
datat['Albanian_lang']=numpy.where(datat.iloc[:,3].str.contains("Albanian",case=False),1,0)
datat['French_lang']=numpy.where(datat.iloc[:,3].str.contains("French",case=False),1,0)
datat['Romanian_lang']=numpy.where(datat.iloc[:,3].str.contains("Romanian",case=False),1,0)
datat['Croatian_lang']=numpy.where(datat.iloc[:,3].str.contains("Croatian",case=False),1,0)
datat['Polish_lang']=numpy.where(datat.iloc[:,3].str.contains("Polish",case=False),1,0)
datat['Lithuanian_lang']=numpy.where(datat.iloc[:,3].str.contains("Lithuanian",case=False),1,0)
datat['Maltese_lang']=numpy.where(datat.iloc[:,3].str.contains("Maltese",case=False),1,0)
datat['Finnish_lang']=numpy.where(datat.iloc[:,3].str.contains("Finnish",case=False),1,0)
datat['Spanish_lang']=numpy.where(datat.iloc[:,3].str.contains("Spanish",case=False),1,0)
datat['Slovene_lang']=numpy.where(datat.iloc[:,3].str.contains("Slovene",case=False),1,0)
datat['Norwegian_lang']=numpy.where(datat.iloc[:,3].str.contains("Norwegian",case=False),1,0)
datat['Montenegrin_lang']=numpy.where(datat.iloc[:,3].str.contains("Montenegrin",case=False),1,0)
datat['Russian_lang']=numpy.where(datat.iloc[:,3].str.contains("Russian",case=False),1,0)
datat['Bosnian_lang']=numpy.where(datat.iloc[:,3].str.contains("Bosnian",case=False),1,0)
datat['Turkish_lang']=numpy.where(datat.iloc[:,3].str.contains("Turkish",case=False),1,0)
datat['Dutch_lang']=numpy.where(datat.iloc[:,3].str.contains("Dutch",case=False),1,0)
datat['Armenian_lang']=numpy.where(datat.iloc[:,3].str.contains("Armenian",case=False),1,0)
datat['Ukrainian_lang']=numpy.where(datat.iloc[:,3].str.contains("Ukrainian",case=False),1,0)
datat['Portuguese_lang']=numpy.where(datat.iloc[:,3].str.contains("Portuguese",case=False),1,0)
datat['Imaginary_lang']=numpy.where(datat.iloc[:,3].str.contains("Imaginary",case=False),1,0)
datat['Swedish_lang']=numpy.where(datat.iloc[:,3].str.contains("Swedish",case=False),1,0)
datat['Samogitian_lang']=numpy.where(datat.iloc[:,3].str.contains("Samogitian",case=False),1,0)
datat['Estonian_lang']=numpy.where(datat.iloc[:,3].str.contains("Estonian",case=False),1,0)
datat['Hungarian_lang']=numpy.where(datat.iloc[:,3].str.contains("Hungarian",case=False),1,0)

In [361]:
del datat['Song language']
#datat.columns.values
del datat['Artist   ']
del datat['Song   ']
del datat['English translation ']


dataframet=datat


In [368]:
X_tdf = pandas.concat([dataframet.iloc[:,0:12].reset_index(drop=True), dataframet.iloc[:,59:92]], axis=1)
XT=X_tdf.values

In [370]:
# predictions
predictions = model.predict_classes(XT, verbose=0)
print(predictions)

[7 7 7 9 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


In [390]:
datav=pandas.read_csv("test_withlabels.csv",skiprows=[1],encoding = "ISO-8859-1")
datav=datav.fillna(0)
actuals=datav.iloc[:,16].values
error=sum(abs(actuals-predictions))
print(error) 

130.0


In [409]:
datav.columns.values[16]

'Albania '

In [424]:
datav.columns.values

array(['Year', 'Country   ', 'Region', 'Song language', 'Artist   ',
       'Song   ', 'English translation ', 'Artist gender', 'Group/Solo',
       'Place', 'Points', 'Host Country', 'Host region',
       'Home/Away Country', 'Home/Away Region',
       'Approximate Betting Prices', 'Albania ', 'Andorra ', 'Armenia ',
       'Austria', 'Azerbaijan ', 'Belarus ', 'Belgium ',
       'Bosnia and Herzegovina ', 'Bulgaria ', 'Croatia ', 'Cyprus ',
       'Czech Republic ', 'Denmark ', 'Estonia ', 'Finland ', 'France ',
       'Georgia', 'Germany ', 'Greece ', 'Hungary ', 'Iceland ',
       'Ireland ', 'Israel ', 'Latvia ', 'Lithuania ', 'Macedonia ',
       'Malta ', 'Moldova ', 'Monaco', 'Montenegro ', 'Netherlands ',
       'Norway ', 'Poland ', 'Portugal ', 'Romania ', 'Russia ',
       'San Marino', 'Serbia ', 'Serbia & Montenegro', 'Slovakia ',
       'Slovenia ', 'Spain ', 'Sweden ', 'Switzerland ', 'Turkey ',
       'Ukraine ', 'United Kingdom '], dtype=object)

In [425]:
def save_model(model,var):
    # saving model
    json_model = model.to_json()
    open(var.split(' ')[0] + 'model_architecture.json', 'w').write(json_model)
    # saving weights
    model.save_weights(var.split(' ')[0] + 'model_weights.h5', overwrite=True)

def load_model(var):
    # loading model
    model = model_from_json(open(var.split(' ')[0] + 'model_architecture.json').read())
    model.load_weights(var.split(' ')[0] + 'model_weights.h5')
    model.compile(loss='categorical_crossentropy', optimizer='adam')
    return model

In [426]:
# save
save_model(model,Y_df.columns.values[0])

# load
model = load_model(Y_df.columns.values[0])


In [422]:
var="mani kanta \ asdfa\aqdsf"

In [423]:
var.split(' ')[0]


'mani kanta '

In [430]:
import pandas
import numpy
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from keras.models import model_from_json

def save_model(model,var):
    # saving model
    json_model = model.to_json()
    open(var.split(' ')[0] + 'model_architecture.json', 'w').write(json_model)
    # saving weights
    model.save_weights(var.split(' ')[0] + 'model_weights.h5', overwrite=True)

def load_model(var):
    # loading model
    model = model_from_json(open(var.split(' ')[0] + 'model_architecture.json').read())
    model.load_weights(var.split(' ')[0] + 'model_weights.h5')
    model.compile(loss='categorical_crossentropy', optimizer='adam')
    return model

def pre_process(dataf):	
	dataf=dataf.fillna(0)
	dataf.iloc[:,7]=dataf.iloc[:,7].replace(["Male","Female","Both","0"],['1','2','3','4'])
	dataf.iloc[:,8]=dataf.iloc[:,8].replace(['Solo', 'Group', 0],['1','2','3'])
	dataf.iloc[:,13]=dataf.iloc[:,13].replace(['Away', 'Home'],['1','2'])
	dataf.iloc[:,14]=dataf.iloc[:,14].replace(['Away', 'Home'],['1','2'])
	
	dataf.iloc[:,1]=dataf.iloc[:,1].replace(['United Kingdom', 'Albania', 'Germany', 'Armenia',
		   'Bosnia and Herzegovina', 'Israel', 'Finland ', 'Croatia', 'Poland',
		   'Iceland', 'Turkey', 'Portugal', 'Latvia', 'Sweden', 'Denmark',
		   'Georgia', 'Ukraine', 'France', 'Azerbaijan', 'Greece', 'Spain',
		   'Serbia', 'Russia', 'Norway', 'Belarus', 'Ireland', 'Macedonia',
		   'Slovenia', 'Hungary', 'Lithuania', 'Romania', 'Bulgaria',
		   'Moldova', 'Switzerland', 'Malta', 'Cyprus',
		   'Serbia and Montenegro', 'Austria', 'Netherlands', 'Belgium',
		   'Estonia', 'Finland', 'Slovakia'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42])
	dataf.iloc[:,2]=dataf.iloc[:,2].replace(['Independent', 'Former Socialist Bloc', 'Western Europe',
		   'Former Yugoslavia', 'Scandinavia'],[0,1,2,3,4])
	dataf.iloc[:,11]=dataf.iloc[:,11].replace(['United Kingdom', 'Albania', 'Germany', 'Armenia',
		   'Bosnia and Herzegovina', 'Israel', 'Finland ', 'Croatia', 'Poland',
		   'Iceland', 'Turkey', 'Portugal', 'Latvia', 'Sweden', 'Denmark',
		   'Georgia', 'Ukraine', 'France', 'Azerbaijan', 'Greece', 'Spain',
		   'Serbia', 'Russia', 'Norway', 'Belarus', 'Ireland', 'Macedonia',
		   'Slovenia', 'Hungary', 'Lithuania', 'Romania', 'Bulgaria',
		   'Moldova', 'Switzerland', 'Malta', 'Cyprus',
		   'Serbia and Montenegro', 'Austria', 'Netherlands', 'Belgium',
		   'Estonia', 'Finland', 'Slovakia'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42])
	dataf.iloc[:,12]=dataf.iloc[:,12].replace(['Independent', 'Former Socialist Bloc', 'Western Europe',
		   'Former Yugoslavia', 'Scandinavia'],[0,1,2,3,4])
	dataf['English_lang']=numpy.where(dataf.iloc[:,3].str.contains("English",case=False),1,0)
	dataf['Hebrew_lang']=numpy.where(dataf.iloc[:,3].str.contains("Hebrew",case=False),1,0)
	dataf['Macedonian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Macedonian",case=False),1,0)
	dataf['Italian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Italian",case=False),1,0)
	dataf['German_lang']=numpy.where(dataf.iloc[:,3].str.contains("German",case=False),1,0)
	dataf['Styrian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Styrian",case=False),1,0)
	dataf['Serbian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Serbian",case=False),1,0)
	dataf['Greek_lang']=numpy.where(dataf.iloc[:,3].str.contains("Greek",case=False),1,0)
	dataf['Slovak_lang']=numpy.where(dataf.iloc[:,3].str.contains("Slovak",case=False),1,0)
	dataf['Albanian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Albanian",case=False),1,0)
	dataf['French_lang']=numpy.where(dataf.iloc[:,3].str.contains("French",case=False),1,0)
	dataf['Romanian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Romanian",case=False),1,0)
	dataf['Croatian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Croatian",case=False),1,0)
	dataf['Polish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Polish",case=False),1,0)
	dataf['Lithuanian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Lithuanian",case=False),1,0)
	dataf['Maltese_lang']=numpy.where(dataf.iloc[:,3].str.contains("Maltese",case=False),1,0)
	dataf['Finnish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Finnish",case=False),1,0)
	dataf['Spanish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Spanish",case=False),1,0)
	dataf['Slovene_lang']=numpy.where(dataf.iloc[:,3].str.contains("Slovene",case=False),1,0)
	dataf['Norwegian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Norwegian",case=False),1,0)
	dataf['Montenegrin_lang']=numpy.where(dataf.iloc[:,3].str.contains("Montenegrin",case=False),1,0)
	dataf['Russian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Russian",case=False),1,0)
	dataf['Bosnian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Bosnian",case=False),1,0)
	dataf['Turkish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Turkish",case=False),1,0)
	dataf['Dutch_lang']=numpy.where(dataf.iloc[:,3].str.contains("Dutch",case=False),1,0)
	dataf['Armenian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Armenian",case=False),1,0)
	dataf['Ukrainian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Ukrainian",case=False),1,0)
	dataf['Portuguese_lang']=numpy.where(dataf.iloc[:,3].str.contains("Portuguese",case=False),1,0)
	dataf['Imaginary_lang']=numpy.where(dataf.iloc[:,3].str.contains("Imaginary",case=False),1,0)
	dataf['Swedish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Swedish",case=False),1,0)
	dataf['Samogitian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Samogitian",case=False),1,0)
	dataf['Estonian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Estonian",case=False),1,0)
	dataf['Hungarian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Hungarian",case=False),1,0)
	del dataf['Song language']
	#dataf.columns.values
	del dataf['Artist   ']
	del dataf['Song   ']
	del dataf['English translation ']
	return dataf

def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(16, input_dim=ins, activation='relu'))
	model.add(Dense(outs, activation='softmax'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
	
dataf=pandas.read_csv("train.csv",skiprows=[1],encoding = "ISO-8859-1")
dataframe=pre_process(dataf)

# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

dataset = dataframe.values
X_df = pandas.concat([dataframe.iloc[:,0:12].reset_index(drop=True), dataframe.iloc[:,59:92]], axis=1)
Y_df=dataframe.iloc[:,12:59]
X=X_df.values
ins=len(X_df.columns.values)


Accuracy: 28.05% (38.90%)


C:\Anaconda2\envs\videoken\lib\site-packages\keras\models.py:848: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
146.0


In [ ]:
for i in range(1,47):

	Y=Y_df.iloc[:,i-1].values		##########
	outs=len(Y_df.iloc[:,i-1].unique())##########

	# encode class values as integers
	encoder = LabelEncoder()
	encoder.fit(Y)
	encoded_Y = encoder.transform(Y)
	# convert integers to dummy variables (i.e. one hot encoded)
	dummy_y = np_utils.to_categorical(encoded_Y)
	estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)
	kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
	results = cross_val_score(estimator, X, dummy_y, cv=kfold)
	print("Var "+ str(i)+"  Accuracy: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

	model = baseline_model()
	model.fit(X, dummy_y, nb_epoch=200, batch_size=5, verbose=0)

	# save and load model
	save_model(model,Y_df.columns.values[i-1])##########
	model = load_model(Y_df.columns.values[i-1])##########

	datat=pandas.read_csv("test.csv",skiprows=[1],encoding = "ISO-8859-1")
	dataframet=pre_process(datat)

	X_tdf = pandas.concat([dataframet.iloc[:,0:12].reset_index(drop=True), dataframet.iloc[:,59:92]], axis=1)
	XT=X_tdf.values
	print(Y_df.columns.values[i-1])
	# predictions
	predictions = model.predict_classes(XT, verbose=0)
	print(predictions)

	datav=pandas.read_csv("test_withlabels.csv",skiprows=[1],encoding = "ISO-8859-1")
	datav=datav.fillna(0)
	actuals=datav.iloc[:,i+15].values ##########
	error=sum(abs(actuals-predictions))
	print("Error for Var" + str(i) + " is: " +  str(error)) 

Var 1  Accuracy: 2.26% (3.02%)


C:\Anaconda2\envs\videoken\lib\site-packages\keras\models.py:848: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Albania 
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
Error for Var1 is: 112.0
Var 2  Accuracy: 11.87% (26.96%)
Andorra 
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
Error for Var2 is: 86
Var 3  Accuracy: 18.49% (36.05%)
Armenia 
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
Error for Var3 is: 98.0
Var 4  Accuracy: 3.03% (2.83%)
Austria
[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]
Error for Var4 is: 240.0
Var 5  Accuracy: 19.62% (38.32%)
Azerbaijan 
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
Error for Var5 is: 87.0
Var 6  Accuracy: 26.57% (38.19%)
Belarus 
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
Error for Var6 is: 76
Var 7  Accuracy: 25.67% (28.28%)
Belgium 
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
Error for Var7 is: 76
Var 8  Accuracy: 10.06% (19.02%)
Bosnia and Herzegovina 
[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]
Error for Var8 is: 186.0
