In [1]:
import pandas
import numpy
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from keras.models import model_from_json
from keras.wrappers.scikit_learn import KerasRegressor

def save_model(model,var):
    # saving model
    json_model = model.to_json()
    open(var.split(' ')[0] + 'model_architecture.json', 'w').write(json_model)
    # saving weights
    model.save_weights(var.split(' ')[0] + 'model_weights.h5', overwrite=True)

def load_model(var):
    # loading model
    model = model_from_json(open(var.split(' ')[0] + 'model_architecture.json').read())
    model.load_weights(var.split(' ')[0] + 'model_weights.h5')
    model.compile(loss='categorical_crossentropy', optimizer='adam')
    return model

def pre_process(dataf):	
	dataf=dataf.fillna(0)
	dataf.iloc[:,7]=dataf.iloc[:,7].replace(["Male","Female","Both","0"],['1','2','3','4'])
	dataf.iloc[:,8]=dataf.iloc[:,8].replace(['Solo', 'Group', 0],['1','2','3'])
	dataf.iloc[:,13]=dataf.iloc[:,13].replace(['Away', 'Home'],['1','2'])
	dataf.iloc[:,14]=dataf.iloc[:,14].replace(['Away', 'Home'],['1','2'])
	
	dataf.iloc[:,1]=dataf.iloc[:,1].replace(['United Kingdom', 'Albania', 'Germany', 'Armenia',
		   'Bosnia and Herzegovina', 'Israel', 'Finland ', 'Croatia', 'Poland',
		   'Iceland', 'Turkey', 'Portugal', 'Latvia', 'Sweden', 'Denmark',
		   'Georgia', 'Ukraine', 'France', 'Azerbaijan', 'Greece', 'Spain',
		   'Serbia', 'Russia', 'Norway', 'Belarus', 'Ireland', 'Macedonia',
		   'Slovenia', 'Hungary', 'Lithuania', 'Romania', 'Bulgaria',
		   'Moldova', 'Switzerland', 'Malta', 'Cyprus',
		   'Serbia and Montenegro', 'Austria', 'Netherlands', 'Belgium',
		   'Estonia', 'Finland', 'Slovakia'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42])
	dataf.iloc[:,2]=dataf.iloc[:,2].replace(['Independent', 'Former Socialist Bloc', 'Western Europe',
		   'Former Yugoslavia', 'Scandinavia'],[0,1,2,3,4])
	dataf.iloc[:,11]=dataf.iloc[:,11].replace(['United Kingdom', 'Albania', 'Germany', 'Armenia',
		   'Bosnia and Herzegovina', 'Israel', 'Finland ', 'Croatia', 'Poland',
		   'Iceland', 'Turkey', 'Portugal', 'Latvia', 'Sweden', 'Denmark',
		   'Georgia', 'Ukraine', 'France', 'Azerbaijan', 'Greece', 'Spain',
		   'Serbia', 'Russia', 'Norway', 'Belarus', 'Ireland', 'Macedonia',
		   'Slovenia', 'Hungary', 'Lithuania', 'Romania', 'Bulgaria',
		   'Moldova', 'Switzerland', 'Malta', 'Cyprus',
		   'Serbia and Montenegro', 'Austria', 'Netherlands', 'Belgium',
		   'Estonia', 'Finland', 'Slovakia'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42])
	dataf.iloc[:,12]=dataf.iloc[:,12].replace(['Independent', 'Former Socialist Bloc', 'Western Europe',
		   'Former Yugoslavia', 'Scandinavia'],[0,1,2,3,4])
	dataf['English_lang']=numpy.where(dataf.iloc[:,3].str.contains("English",case=False),1,0)
	dataf['Hebrew_lang']=numpy.where(dataf.iloc[:,3].str.contains("Hebrew",case=False),1,0)
	dataf['Macedonian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Macedonian",case=False),1,0)
	dataf['Italian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Italian",case=False),1,0)
	dataf['German_lang']=numpy.where(dataf.iloc[:,3].str.contains("German",case=False),1,0)
	dataf['Styrian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Styrian",case=False),1,0)
	dataf['Serbian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Serbian",case=False),1,0)
	dataf['Greek_lang']=numpy.where(dataf.iloc[:,3].str.contains("Greek",case=False),1,0)
	dataf['Slovak_lang']=numpy.where(dataf.iloc[:,3].str.contains("Slovak",case=False),1,0)
	dataf['Albanian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Albanian",case=False),1,0)
	dataf['French_lang']=numpy.where(dataf.iloc[:,3].str.contains("French",case=False),1,0)
	dataf['Romanian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Romanian",case=False),1,0)
	dataf['Croatian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Croatian",case=False),1,0)
	dataf['Polish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Polish",case=False),1,0)
	dataf['Lithuanian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Lithuanian",case=False),1,0)
	dataf['Maltese_lang']=numpy.where(dataf.iloc[:,3].str.contains("Maltese",case=False),1,0)
	dataf['Finnish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Finnish",case=False),1,0)
	dataf['Spanish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Spanish",case=False),1,0)
	dataf['Slovene_lang']=numpy.where(dataf.iloc[:,3].str.contains("Slovene",case=False),1,0)
	dataf['Norwegian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Norwegian",case=False),1,0)
	dataf['Montenegrin_lang']=numpy.where(dataf.iloc[:,3].str.contains("Montenegrin",case=False),1,0)
	dataf['Russian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Russian",case=False),1,0)
	dataf['Bosnian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Bosnian",case=False),1,0)
	dataf['Turkish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Turkish",case=False),1,0)
	dataf['Dutch_lang']=numpy.where(dataf.iloc[:,3].str.contains("Dutch",case=False),1,0)
	dataf['Armenian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Armenian",case=False),1,0)
	dataf['Ukrainian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Ukrainian",case=False),1,0)
	dataf['Portuguese_lang']=numpy.where(dataf.iloc[:,3].str.contains("Portuguese",case=False),1,0)
	dataf['Imaginary_lang']=numpy.where(dataf.iloc[:,3].str.contains("Imaginary",case=False),1,0)
	dataf['Swedish_lang']=numpy.where(dataf.iloc[:,3].str.contains("Swedish",case=False),1,0)
	dataf['Samogitian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Samogitian",case=False),1,0)
	dataf['Estonian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Estonian",case=False),1,0)
	dataf['Hungarian_lang']=numpy.where(dataf.iloc[:,3].str.contains("Hungarian",case=False),1,0)
	del dataf['Song language']
	#dataf.columns.values
	del dataf['Artist   ']
	del dataf['Song   ']
	del dataf['English translation ']
	return dataf

def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(30, input_dim=ins, activation='relu'))
	model.add(Dense(outs, activation='relu'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
	
dataf=pandas.read_csv("train.csv",skiprows=[1],encoding = "ISO-8859-1")
dataframe=pre_process(dataf)

# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

dataset = dataframe.values
X_df = pandas.concat([dataframe.iloc[:,0:12].reset_index(drop=True), dataframe.iloc[:,59:92]], axis=1)
Y_df=dataframe.iloc[:,12:59]
X=X_df.values
ins=len(X_df.columns.values)


Using TensorFlow backend.


In [ ]:
for i in range(1,47):

	Y=Y_df.iloc[:,i-1].values		##########
	outs=len(Y_df.iloc[:,i-1].unique())##########

	# encode class values as integers
	encoder = LabelEncoder()
	encoder.fit(Y)
	encoded_Y = encoder.transform(Y)
	# convert integers to dummy variables (i.e. one hot encoded)
	dummy_y = np_utils.to_categorical(encoded_Y)
	estimator = KerasRegressor(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)
	kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
	results = cross_val_score(estimator, X, dummy_y, cv=kfold)
	print("Var "+ str(i)+"  Accuracy: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

	model = baseline_model()
	model.fit(X, dummy_y, nb_epoch=200, batch_size=5, verbose=0)

	# save and load model
	save_model(model,Y_df.columns.values[i-1])##########
	model = load_model(Y_df.columns.values[i-1])##########

	datat=pandas.read_csv("test.csv",skiprows=[1],encoding = "ISO-8859-1")
	dataframet=pre_process(datat)

	X_tdf = pandas.concat([dataframet.iloc[:,0:12].reset_index(drop=True), dataframet.iloc[:,59:92]], axis=1)
	XT=X_tdf.values
	print(Y_df.columns.values[i-1])
	# predictions
	predictions = model.predict_classes(XT, verbose=0)
	print(predictions)

	datav=pandas.read_csv("test_withlabels.csv",skiprows=[1],encoding = "ISO-8859-1")
	datav=datav.fillna(0)
	actuals=datav.iloc[:,i+15].values ##########
	error=sum(abs(actuals-predictions))
	print("Error for Var" + str(i) + " is: " +  str(error)) 

Var 1  Accuracy: nan% (nan%)


C:\Anaconda2\envs\videoken\lib\site-packages\keras\models.py:848: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Albania 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Error for Var1 is: 58.0
Var 2  Accuracy: 878.13% (639.13%)
Andorra 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Error for Var2 is: 58
Var 3  Accuracy: nan% (nan%)
Armenia 
[1 4 4 1 1 4 4 1 4 4 4 1 4 4 4 1 4 1 4 4 1 4 4 4]
Error for Var3 is: 64.0
Var 4  Accuracy: nan% (nan%)
Austria
[7 9 9 7 7 9 9 9 9 9 9 7 9 9 9 9 9 9 9 9 7 9 9 9]
Error for Var4 is: 206.0
Var 5  Accuracy: nan% (nan%)
Azerbaijan 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Error for Var5 is: 57.0
Var 6  Accuracy: nan% (nan%)
Belarus 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Error for Var6 is: 58
